package parser;

import java.util.List;
import java.util.ArrayList;
import tokenizer.Token;
import evaluator.*;

public class Parser{
    private List<Token> tokens; // List of tokens generated by tokenizer
    private int index = 0; // Pointing to current index in tokens list

    public Parser(List<Token> tokens){
        this.tokens = tokens;
    }

    // Returns current token without consuming it
    private Token peek() {
        if(index >= tokens.size()){
            return tokens.get(tokens.size() - 1); // Return last token if out of bounds
        }
        return tokens.get(index);
    }

    // Checks whether it reached end of the tokens list
    private boolean isEnd() { 
        return peek().type() == Token.Type.EOF; 
    }

    // Moves to next token and returns previous one
    private Token advance(){
        if(!isEnd()){
            index++;
        }
        return tokens.get(index - 1);
    }

    // Checks if current token matches given type
    private boolean check(Token.Type type){
        if(isEnd()){
            return false;
        }
        return peek().type() == type;
    }

    // If token matches, consume it and return true
    private boolean match(Token.Type type){
        if(check(type)){
            advance();
            return true;
        }
        else{
            return false;
        }
    }

    // parses entire token list into instructions
    public List<Instruction> parse(){
        List<Instruction> instructions = new ArrayList<>();
        while(!isEnd()){
            // if(check(Token.Type.NEWLINE)){ // skip empty lines
            while(check(Token.Type.NEWLINE)){ // skip all consecutive newlines
                advance();
            }
            if(isEnd()){ // if end after skipping newlines, break
                break;
            }
            instructions.add(parseInstruction());
        }
        return instructions;
    }

    private Instruction parseInstruction(){ // Parses a single instruction based on token type
        if(check(Token.Type.IDENTIFIER)){
            advance();
            return parseAssignment(); // variable assignment
        }
        else if(check(Token.Type.PRINT)){
            advance();
            return parsePrint(); // print statement
        }
        else if(check(Token.Type.IF)){
            advance();
            return parseIf(); // conditional statement
        }
        else if(check(Token.Type.REPEAT)){
            advance();
            return parseRepeat(); // loop statement
        }
        else{
            throw new RuntimeException("Unexpected token: " + peek().lexeme());
        }
    }

    // Parses assignment, variable := expression
    private Instruction parseAssignment(){
        String var = tokens.get(index - 1).lexeme();
        if(!check(Token.Type.ASSIGN)){
            throw new RuntimeException("Expected ':=' after identifier");
        }
        advance(); // consume ':='
        Expression expr = parseExpression();
        return new AssignInstruction(var, expr);
    }

    // Parses expressions with +, -, >, <, ==
    private Expression parseExpression(){
        Expression left = parseTerm();
        while(check(Token.Type.PLUS) || check(Token.Type.MINUS) || check(Token.Type.GT) || check(Token.Type.LT) || check(Token.Type.EQ)){
            Token operator = advance();
            Expression right = parseTerm();
            // Build binary expression tree
            BinaryOpNode node = new BinaryOpNode(left, operator.lexeme(), right);
            left = node;
        }
        return left;
    }

    // Parses multiplication and division
    private Expression parseTerm(){
        Expression left = parsePrimary();
        while(check(Token.Type.MULTIPLY) || check(Token.Type.DIVIDE)){
            Token operator = advance();
            Expression right = parsePrimary();
            BinaryOpNode node = new BinaryOpNode(left, operator.lexeme(), right);
            left = node;
        }
        return left;
    }

    // Parses number, string, variable
    private Expression parsePrimary(){
        if(check(Token.Type.NUMBER)){
            Token t = advance();
            return new NumberNode((Double) t.literal());
        }
        else if(check(Token.Type.STRING)){
            Token t = advance();
            return new StringNode((String) t.literal());
        }
        else if(check(Token.Type.IDENTIFIER)){
            Token t = advance();
            return new VariableNode(t.lexeme());
        }
        else{
            throw new RuntimeException("Unexpected token: " + peek().lexeme());
        }
    }

    // Parses print statement
    private Instruction parsePrint(){
        Expression expr = parseExpression();
        return new PrintInstruction(expr);
    }

    // Parses if condition => instruction
    private Instruction parseIf(){
        Expression condition = parseExpression();
        if(!check(Token.Type.ARROW)){
            throw new RuntimeException("Expected '=>' after condition");
        }
        advance(); // consume '=>'
        List<Instruction> body = new ArrayList<>();
        while(check(Token.Type.NEWLINE)){ // skip newlines after if body
            advance();
        }
        while(!isEnd() && !check(Token.Type.IF) && !check(Token.Type.REPEAT)){
            if(check(Token.Type.NEWLINE)){
                advance();
                continue;
            }
            body.add(parseInstruction());
        }
        return new IfInstruction(condition, body);
    }

    // Parses repeat loop: repeat expression => instruction
    private Instruction parseRepeat(){
        Expression times = parseExpression();
        if(!check(Token.Type.ARROW)){
            throw new RuntimeException("Expected '=>' after times expression");
        }
        advance(); // consume '=>'
        List<Instruction> body = new ArrayList<>();
        while(check(Token.Type.NEWLINE)){ // skip newlines after repeat body
            advance();
        }
        while(!isEnd() && !check(Token.Type.IF) && !check(Token.Type.REPEAT)){
            if(check(Token.Type.NEWLINE)){
                advance();
                continue;
            }
            body.add(parseInstruction());
        }
        return new RepeatInstruction(times, body);
    }
}